import type { CSSProperties } from "react";

export const dentalTheme = {
  colors: {
    background: "#f7f7f8",
    surface: "#ffffff",
    heading: "#1a1c21",
    body: "#2a2d33",
    muted: "#5a5f69",
    accent: "#fc5e3b",
    accentHover: "#e14d2d",
    accentSoft: "#ffe9e3",
    accentBorder: "#ffc0b1",
    border: "#d8dbe1",
    borderSoft: "#e9ebef",
    deepSurface: "#1f232a",
    deepText: "#cfd3da",
    deepAccent: "#9aa1ab",
    black: "#111111",
    white: "#ffffff",
    logoOrange: "#fc5e3b",
    logoBlue: "#1f232a",
  },
} as const;

export const dentalThemeVars = {
  "--color-bg": dentalTheme.colors.background,
  "--color-surface": dentalTheme.colors.surface,
  "--color-heading": dentalTheme.colors.heading,
  "--color-body": dentalTheme.colors.body,
  "--color-muted": dentalTheme.colors.muted,
  "--color-accent": dentalTheme.colors.accent,
  "--color-accent-hover": dentalTheme.colors.accentHover,
  "--color-accent-soft": dentalTheme.colors.accentSoft,
  "--color-accent-border": dentalTheme.colors.accentBorder,
  "--color-border": dentalTheme.colors.border,
  "--color-border-soft": dentalTheme.colors.borderSoft,
  "--color-deep-surface": dentalTheme.colors.deepSurface,
  "--color-deep-text": dentalTheme.colors.deepText,
  "--color-deep-accent": dentalTheme.colors.deepAccent,
  "--color-black": dentalTheme.colors.black,
  "--color-white": dentalTheme.colors.white,
  "--color-logo-orange": dentalTheme.colors.logoOrange,
  "--color-logo-blue": dentalTheme.colors.logoBlue,
} as CSSProperties;
